Clarify that cache is not strictly necessary
codingjoe/django-select2 pull request #16
Opened 2020-10-27 10:32 UTC by abeforgit

While it is definitely a good idea to stress the importance of a good cache setup, the current docs make it sound like it won't work at all without, which doesn't seem to be the case. For quick tests and small-scale projects it is good to know that it will run fine without.

2020-11-02 07:24 UTC, jieter commented on docs/index.rst
> +While not strictly necessary for django-select to work, for performance reasons it is highly recommended to setup a persistent cache backend (NOT
I suggest using the exact project name (django-select2)

```suggestion
While not strictly necessary for django-select2 to work, for performance reasons it is highly recommended to setup a persistent cache backend (NOT
```

You might consider adhering to the surrounding line length (or at least use "Semantic Line Breaks" https://sembr.org/).

2020-11-09 13:40 UTC, solarissmoke commented
I think the assertion that a cache isn't required is false. You can verify this by running this package with the cache entirely disabled (i.e.,g use the Django `DummyCache`) as a backend: it will not work at all. [This bit of code](https://github.com/codingjoe/django-select2/blob/master/django_select2/views.py#L84-L87) will always raise a 404 error because there is never anything in the cache. So instead of saying that a cache is optional, I think the documentation in fact needs to state that *a working cache backend is mandatory*.

There's a more fundamental problem, which is that if things fall out of the cache then the behaviour breaks. The code is not only assuming the presence of a cache, but of a *persistent cache that never culls anything*. This was alluded to [in this issue](https://github.com/applegrew/django-select2/issues/243), where the conversation didn't go so well, but I think the original point is valid: it's very easy to break a widget just because it's cache entry was removed for any reason.

2020-11-09 17:51 UTC, jpm92 commented
> I think the assertion that a cache isn't required is false. You can verify this by running with the cache entirely disabled (i.e., use the Django `DummyCache`) as a backend: it will not work at all. [This bit of code](https://github.com/codingjoe/django-select2/blob/master/django_select2/views.py#L84-L87) will always raise a 404 error because there is never anything in the cache.
> 
> The code is not only assuming the presence of a cache, but of a _persistent cache that never culls anything_. This was alluded to [in this issue](https://github.com/applegrew/django-select2/issues/243), where the conversation didn't go so well, but I think the original point is valid: it's very easy to break a widget just because it's cache entry was removed for any reason. This is easy to demonstrate with the `LocMemCache` in development - just restarting the Django server while using a widget on a page is sufficient to make it stop working.

Well, I'm using it at the moment with the default django cache and I facing no issues sofar...

2020-11-12 10:12 UTC, abeforgit commented on docs/index.rst
> +While not strictly necessary for django-select to work, for performance reasons it is highly recommended to setup a persistent cache backend (NOT
Good suggestions, applied!

2020-11-12 10:20 UTC, abeforgit commented
Im using the default cache (which from the django docs I gather is the LocMemCache), which is also not persistent, with no issues.
Sure maybe it's not the best thing to do and definitely not for a heavy-use production app, but how many of us came here to just get a working select with the least amount of setup for their 5-user demo app?

2020-12-15 11:26 UTC, codingjoe approved these changes
Works for me thanks @abeforgit

2020-12-15 11:30 UTC, codingjoe requested changes
Wait, actually it doesn't work for me. The cache needs to be `persistent`, not matter the setup. If you use a single app node setup, of course you don't need a cache that is persistent across mutliple nodes, thus `LocMemCache` would do.

The paragraph was introduced because I got many people reporting problems because they forgot to set up a persistent cache. I know it makes initial set up a little harder, but I don't see a way around it.

2020-12-15 11:31 UTC, codingjoe commented
That being said, I welcome changes on the docs and this paragraph too. Maybe you can rewrite it a little be more comprehencive.

2020-12-15 13:34 UTC, abeforgit commented
Ah I think that is indeed the source of most of the confusion. Ill rewrite it sometime this week, hopefully tomorrow

2021-04-18 10:20 UTC, abeforgit commented
"Tomorrow" turned out to be about 4 months later... funny how that goes...

2021-04-19 15:48 UTC, codingjoe approved these changes
Hi @abeforgit,

Excellent addition to the docs! Good documentation is key. Great contribution.

Best,
Joe

2021-04-19 15:48 UTC, merged